# Numpy Arrays
(NumPy stands for Numerical Python)


NumPy is a Python library used for working with arrays.It also has functions for working in domain of linear algebra and matrices.


**Why Use NumPy?**


In Python we have lists that serve the purpose of arrays, but they are slow to process.
**NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.**
The array object in NumPy is called **ndarray**, it provides a lot of supporting functions that make working with ndarray very easy.


Installation of NumPy


In [ ]:
%pip install --upgrade pip
%pip install numpy

In [ ]:
#Checking NumPy Version
import numpy as np

print(np.__version__)

Creating a 1D Numpy Array from a List

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)  # Output: [1 2 3 4 5]


Creating a 2D Numpy Array from a List of Lists

In [ ]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)  # Output: [[1 2 3]
             #          [4 5 6]]

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

Creating an Array of Zeros

In [ ]:
zeros = np.zeros((2, 3))
print(zeros)  # Output: [[0. 0. 0.]
              #          [0. 0. 0.]]


Creating an Array of Ones

In [ ]:
ones = np.ones((3, 2))
print(ones)  # Output: [[1. 1.]
             #          [1. 1.]
             #          [1. 1.]]


Creating an Array with a Specific Range

In [ ]:
range_array = np.arange(10)
print(range_array)  # Output: [0 1 2 3 4 5 6 7 8 9]


Creating an Array with a Range of Values and Specific Step Size

In [ ]:
range_step = np.arange(0, 10, 2)
print(range_step)  # Output: [0 2 4 6 8]


Creating an Array of Evenly Spaced Values Between Two Numbers

In [ ]:
linspace_array = np.linspace(0, 1, 5)
print(linspace_array)  # Output: [0.   0.25 0.5  0.75 1.  ]


Creating an Array with Random Values Between 0 and 1


In [ ]:
random_array = np.random.rand(3, 3)
print(random_array)


Creating an Array with Random Integers

In [ ]:
random_integers = np.random.randint(1, 10, (2, 2))
print(random_integers)


Checking the Shape of an Array

The shape of an array is the number of elements in each dimension.

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr)

In [ ]:
print(arr.shape)

Accessing Data Type of Elements

In [ ]:
print(arr.dtype)  # Output: int64

### NumPy Array Slicing
- We pass slice instead of index like this: [start:end].
- We can also define the step, like this: [start:end: step].

Indexing a 1D Array

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # Output: 10
print(arr[-1])  # Output: 50


Slicing a 1D Array

In [ ]:
print(arr[1:4])  # Output: [20 30 40]


Indexing a 2D Array

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0, 2])  # Output: 3


Slicing a 2D Array

In [ ]:
print(arr[1:, 1:])  # Output: [[5 6]
                    #          [8 9]]


Access 3-D Arrays

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

Additional array slicing syntax

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

In [ ]:
#Adding Step
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:3])

In [ ]:
# Skipping start
print(arr[::2])

In [ ]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

Element-wise Addition

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)  # Output: [5 7 9]


Array Broadcasting

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr + 10)  # Output: [[11 12 13]
                 #          [14 15 16]]


In [ ]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

In [ ]:
a + b

Matrix Multiplication

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(np.dot(arr1, arr2))  # Output: [[19 22]
                           #          [43 50]]


Calculating Mean and Sum

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))  # Output: 3.0
print(np.sum(arr))   # Output: 15


Finding Maximum and Minimum Values

In [ ]:
print(np.max(arr))  # Output: 5
print(np.min(arr))  # Output: 1


### Array Concatenation
Joining means putting contents of two or more arrays in a single array.


In [ ]:
arr1 = np.array([1, 2, 3,6])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

Join two 2-D arrays along rows (axis=1):

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)


Join two 2-D arrays along rows (axis=1):

In [ ]:
#Join two 2-D arrays along columns (axis=0):
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)


You can also concatenate more than two arrays at once:

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([99, 99, 99])

print(np.concatenate([x, y, z]))

And it can be used for two-dimensional arrays:

In [ ]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [ ]:
# concatenate along the first axis
np.concatenate([grid, grid])

In [ ]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

For working with arrays of mixed dimensions, it can be clearer to use the `np.vstack` (vertical stack) and `np.hstack` (horizontal stack) functions:

In [ ]:
# vertically stack the arrays
np.vstack([x, grid])

In [ ]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

Similarly, for higher-dimensional arrays, `np.dstack` will stack arrays along the third axis.

### Splitting Array
Splitting is reverse operation of Joining.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6,7])

newarr = np.array_split(arr, 2)

print(newarr)


Another useful type of operation is reshaping of arrays, which can be done with the `reshape` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [ ]:
grid = np.arange(1, 10).reshape(3, 3)

print(grid)

A common reshaping operation is converting a one-dimensional array into a two-dimensional row or column matrix:

In [ ]:
x = np.array([1, 2, 3])

x.reshape((1, 3))  # row vector via reshape

In [ ]:
x.reshape((3, 1))  # column vector via reshape

A convenient shorthand for this is to use `np.newaxis` in the slicing syntax:


In [ ]:
x[np.newaxis, :]  # row vector via newaxis

In [ ]:
x[:, np.newaxis]  # column vector via newaxis

The related functions `np.hsplit` and `np.vsplit` are similar

In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

Similarly, for higher-dimensional arrays, `np.dsplit` will split arrays along the third axis.

# Practical Applications

Square Matrix

In [ ]:
import numpy as np

square_matrix = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])
print("Square Matrix:\n", square_matrix)


Diagonal Matrix

In [ ]:
diagonal_matrix = np.diag([1, 2, 3])
print("Diagonal Matrix:\n", diagonal_matrix)


Identity Matrix

In [ ]:
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)


Upper Triangular Matrix

In [ ]:
upper_triangular = np.array([[1, 2, 3],
                             [0, 5, 6],
                             [0, 0, 9]])
print("Upper Triangular Matrix:\n", upper_triangular)


Lower Triangular Matrix

In [ ]:
lower_triangular = np.array([[1, 0, 0],
                             [4, 5, 0],
                             [7, 8, 9]])
print("Lower Triangular Matrix:\n", lower_triangular)


Symmetric Matrix

In [ ]:
symmetric_matrix = np.array([[1, 2, 3],
                             [2, 5, 6],
                             [3, 6, 9]])
print("Symmetric Matrix:\n", symmetric_matrix)


Transpose of a Matrix

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
transpose_matrix = np.transpose(matrix)
print("Original Matrix:\n", matrix)
print("Transpose of Matrix:\n", transpose_matrix)


Trace of a Matrix

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
trace = np.trace(matrix)
print("Trace of Matrix:", trace)


Determinant of a Matrix

In [ ]:
matrix = np.array([[4, 6],
                   [3, 8]])
determinant = np.linalg.det(matrix)
print("Determinant of Matrix:", determinant)


Inverse of a Matrix

In [ ]:
matrix = np.array([[1, 2],
                   [3, 4]])
inverse_matrix = np.linalg.inv(matrix)
print("Inverse of Matrix:\n", inverse_matrix)


Rank of a Matrix

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
rank = np.linalg.matrix_rank(matrix)
print("Rank of Matrix:", rank)


### Boolean Arrays and Masking



**Comparison Operators**

NumPy also implements comparison operators such as `<` (less than) and `>` (greater than). The result of these comparison operators is always an array with a Boolean data type.


In [ ]:
x = np.array([1, 2, 3, 4, 5])

In [ ]:
x < 3  # less than

In [ ]:
x > 3  # greater than

In [ ]:
x <= 3  # less than or equal

In [ ]:
x >= 3  # greater than or equal

In [ ]:
x != 3  # not equal

In [ ]:
x == 3  # equal

It is also possible to do an element-wise comparison of two arrays, and to include compound expressions:

In [ ]:
(2 * x) == (x ** 2)

As in the case of arithmetic operators, the comparison operators are implemented as ufuncs in NumPy; for example, when you write `x < 3`, internally NumPy uses `np.less(x, 3)`.
    A summary of the comparison operators and their equivalent ufuncs is shown here:

| Operator    | Equivalent ufunc  | Operator   | Equivalent ufunc |
|-------------|-------------------|------------|------------------|
|`==`         |`np.equal`         |`!=`        |`np.not_equal`    |
|`<`          |`np.less`          |`<=`        |`np.less_equal`   |
|`>`          |`np.greater`       |`>=`        |`np.greater_equal`|

## Boolean Arrays as Masks

What makes the Boolean arrays powerful tool is to use them as masks. Let's return to our `x` array from before:

In [ ]:
x

Suppose we want an array of all values in the array that are less than, say, 5. We can obtain a Boolean array for this condition easily, as we've already seen:

In [ ]:
x < 5

Now, to *select* these values from the array, we can simply index on this Boolean array; this is known as a *masking* operation:

In [ ]:
x[x < 5]

What is returned is a one-dimensional array filled with all the values that meet this condition; in other words, all the values in positions at which the mask array is `True`.

### Practical Example:
**Counting Rainy Days**

Imagine you have a series of data that represents the amount of precipitation each day for a year in a given city.
For example, here we'll load the daily rainfall statistics for the city of Seattle in 2015, using Pandas

In [ ]:
import numpy as np
from vega_datasets import data

# Use DataFrame operations to extract rainfall as a NumPy array
rainfall_mm = np.array(
    data.seattle_weather().set_index('date')['precipitation']['2015'])
len(rainfall_mm)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')

In [ ]:
plt.hist(rainfall_mm, 40);

This histogram gives us a general idea of what the data looks like: despite the city's rainy reputation, the vast majority of days in Seattle saw near zero measured rainfall in 2015.
But this doesn't do a good job of conveying some information we'd like to see: for example, how many rainy days were there in the year? What was the average precipitation on those rainy days? How many days were there with more than 10 mm of rainfall?

One approach to this would be to answer these questions by hand: we could loop through the data, incrementing a counter each time we see values in some desired range.
But for reasons discussed throughout this chapter, such an approach is very inefficient from the standpoint of both time writing code and time computing the result.
We saw in [Computation on NumPy Arrays: Universal Functions](02.03-Computation-on-arrays-ufuncs.ipynb) that NumPy's ufuncs can be used in place of loops to do fast element-wise arithmetic operations on arrays; in the same way, we can use other ufuncs to do element-wise *comparisons* over arrays, and we can then manipulate the results to answer the questions we have.
We'll leave the data aside for now, and discuss some general tools in NumPy to use *masking* to quickly answer these types of questions.

Q. How many days there were with more than 10 mm and less than 20 mm of rain?

A. We can accomplish this with Python's *bitwise logic operators*, `&`, `|`, `^`, and `~`.

In [ ]:
np.sum((rainfall_mm > 10) & (rainfall_mm < 20))

Or we can calculate it as:

In [ ]:
np.sum(~( (rainfall_mm <= 10) | (rainfall_mm >= 20) ))

Here are some more examples of results we can compute when combining masking with aggregations:

In [ ]:
print("Number days without rain:  ", np.sum(rainfall_mm == 0))
print("Number days with rain:     ", np.sum(rainfall_mm != 0))
print("Days with more than 10 mm: ", np.sum(rainfall_mm > 10))
print("Rainy days with < 5 mm:    ", np.sum((rainfall_mm > 0) &
                                            (rainfall_mm < 5)))

Using masking to compute some relevant statistics

In [ ]:
# construct a mask of all rainy days
rainy = (rainfall_mm > 0)

# construct a mask of all summer days (June 21st is the 172nd day)
days = np.arange(365)
summer = (days > 172) & (days < 262)

print("Median precip on rainy days in 2015 (mm):   ",
      np.median(rainfall_mm[rainy]))
print("Median precip on summer days in 2015 (mm):  ",
      np.median(rainfall_mm[summer]))
print("Maximum precip on summer days in 2015 (mm): ",
      np.max(rainfall_mm[summer]))
print("Median precip on non-summer rainy days (mm):",
      np.median(rainfall_mm[rainy & ~summer]))